### ISSUE TITLE
Some resources (Not all of them are indexed as papers)

### ISSUE THREAD

**Issue by jiaqingxie** [zita-ch/bipedal-robot-learning-collection#1]
Hi Zita. Here's some supplementary resources I found which might be helpful?

1. Reinforcement Learning for Bipedal walking robot.[https://github.com/navuboy/ddpg_biped](https://github.com/navuboy/ddpg_biped)
2. Hierarchical Control for Bipedal Locomotion using Central Pattern Generators and Neural Networks.[https://github.com/sayantanauddy/hierarchical_bipedal_controller](https://github.com/sayantanauddy/hierarchical_bipedal_controller)
3. The Bipedal Skills Benchmark. [https://github.com/facebookresearch/bipedal-skills](https://github.com/facebookresearch/bipedal-skills)
4. LORM: a novel reinforcement learning framework for biped gait control. [https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9044250/](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9044250/).

One suggestion might be that, apart from the abstract or brief descriptions, it's better to add the code implementation link for each paper or the arXiv link if possible :)

**Comment by jiaqingxie** [comment]
Sorry to bother. I am not sure if listing papers or projects before 2018 should be considered in this domain.  When you are writing papers, would you include some old but useful papers.

**Comment by zita-ch** [comment]
Hi Jiaqing,
Thanks for advice.
Yet, this project focuses on how we can achieve RL on real bipeds, which should not only consider how to represent the complex dynamics, but also how to help the robot learn the real environment.
Therefore, despite the meaningful inspirations from these works, currently they are not to be included.

About code implementation: it makes sense. I will later provide some open-source solution links here, e.g., how ppl train the cassie robot in simulation.
